AZURE_DELTA_LAKE_PATH = 'az://sports/'
LOCAL_DELTA_LAKE_PATH = 'data/deltalake'
OPTIONS={"AZURE_STORAGE_ACCOUNT_NAME":"jioaishared",
 "AZURE_STORAGE_ACCOUNT_KEY":"OYRIjKqneeiI+UrDyLHV7CBOudfdxb73AqkdtUYX3UGYVynUDjQdCtv60a73oEf++qIYnY6844QUOSPrcndLuQ=="}
